### ISSUE TITLE
Combine lyche reservation pages

### ISSUE THREAD

**Issue by aleksanb** [Samfundet/Samfundet#10]
Currently, we have the page https://www.samfundet.no/lyche which links to https://www.samfundet.no/lyche-bordreservasjon which then links to the real reservation page on https://www.samfundet.no/lyche/reservasjon.

I think we should combine the text of the middle info page into the top of the lyche reservation site for consistency.

**Comment by tollefj** [comment]
Going through old issues:
This was "solved" a while ago by adding a table reservation link to [/lyche](https://www.samfundet.no/lyche), as well as in [/lyche-bordreservasjon](https://www.samfundet.no/lyche-bordreservasjon) (which shows information about reservations) thus removing the nested way of finding a reservation, but still keeping the information page.
