### ISSUE TITLE
Dynamic opening hours

### ISSUE THREAD

**Issue by Assios** [Samfundet/Samfundet#11]
Knaus and Rundhallen are always closed according to the opening hours, because the opening hours for these areas are determined by events. Ideally, the opening hours should be automatically updated when events are made for these areas. The opening hours for the specific area pages (like https://www.samfundet.no/daglighallen) should also be inferred from the opening hours instead of being static.

**Comment by tollefj** [comment]
Going through old issues:
The way all "pages" work, which are dynamic based on markdown/html, prevents us to get opening hours from the server in a simple way. A way around this would be to split up pages into pages related to areas, say pages_area and regular pages, such that pages_area looks up the opening hours from the database, as found in the administration panel. Will be considered when rewriting Samfundet.
