### ISSUE TITLE
Separate/tag external events

### ISSUE THREAD

**Issue by alfiehub** [Samfundet/Samfundet#115]
Events held by external organizers needs to be marked so that our visitors dont confuse them with the official Samfundet events.

A boolean field for events and some type of visual notice would be enough.

**Comment by ahammar** [comment]
There is already event.organizer which is a polymorphic field that can be an ExternalOrganizer. Not sure how that is rendered at the moment, but the model side should already be covered.

**Comment by eirikvaa** [comment]
Closing because it seems to be good.
