### ISSUE TITLE
See all tickets on membership card

### ISSUE THREAD

**Issue by Assios** [Samfundet/Samfundet#12]
It would be nice for users to see which tickets they have on their membership card.

**Comment by eirikvaa** [comment]
All tickets are sent on mail, so closing for now.

**Comment by kaprests** [comment]
Would you consider reopening this? I think it would be really nice to have all tickets easily available on the site. Mail quickly fills up with lots of different things, and it can be a little difficult to remember exactly which events you have bought tickets for. This is especially true for when it's UKA with so many events at "once".
