### ISSUE TITLE
Switch back to official mina

### ISSUE THREAD

**Issue by stianste** [Samfundet/Samfundet#14]
Due to mina currently not enforcing host key checking (mina-deploy/mina#361)
we use our own hosted version at https://github.com/Samfundet/mina with the PR merged in.

Once mina gets their things together, we should switch back to the official one.

**Comment by eirikvaa** [comment]
It looks like things have been fixed, so will try to use the official mina and deploy to www-beta to verify.

**Comment by eirikvaa** [comment]
Closed by #482
