### ISSUE TITLE
Refactor user system to have a single user type with multiple logins

### ISSUE THREAD

**Issue by Assios** [Samfundet/Samfundet#18]
ahammar commented on 10 May 2014: "The split between applicants and members and how closely these are tied to the different member databases keeps causing us a lot of headaches.

Idea:

combine members and applicants into a single user type
a user can have multiple login types connected to his/her account
While it will be a big change, this allows us to simplify a lot of code by removing special cases for applicants/members. It also simplifies differences between development and production (mdb2 login is available in prod, but other than that the user object is the same), and as a bonus it opens up the possibility of supporting additional login types in the future such as OpenID, Facebook login, etc."

**Comment by eirikvaa** [comment]
This is quite the change and is probably too much for Web at the moment. Will open again if it becomes reelvant.
