### ISSUE TITLE
Archiving of interesting data

### ISSUE THREAD

**Issue by Anderssorby** [Samfundet/Samfundet#219]
There is a lot of data on the webpage that should be kept and archived for the future. This should be automated and sent to the archiving committee of Samfundet. Some of it is captured by the web archive (the front page and some of the main links.) It is not very often scanned though.

Things that could be archived:

- Applicant statistics
- Old events
- Blog
- ...

**Comment by evgiz** [comment]
Related to #592 
Blog not used

Old events are already archived by Arkivet
Data is still available in database backups by ITK anyway so closing this issue
