### ISSUE TITLE
Opening times are updated before the last venue is closed

### ISSUE THREAD

**Issue by stekern** [Samfundet/Samfundet#234]
The opening hours on the frontpage are currently updated at midnight. This can be confusing for a user in e.g. Daglighallen on a Saturday at 00:01 am who's wondering how long the venue is open. 

A better solution could maybe be updating the opening times after the last venue is closed. And to make it easier to view opening times for different days, the different days could be added as clickable links. See image.

**Current opening times**
![screenshot from 2017-04-27 18-44-34](https://cloud.githubusercontent.com/assets/10640491/25494753/02c97cb4-2b7b-11e7-8574-3beb791fbbbe.png)

**Mockup of proposed solution**
![screenshot from 2017-04-27 18-51-27](https://cloud.githubusercontent.com/assets/10640491/25494772/129953bc-2b7b-11e7-9b9d-a9e36153c17f.png)

**Comment by ghost** [comment]
Opening hours now change at 04:00 (commit #236); can still work on the proposed solution for the ÅPNINGSTIDER UI
