### ISSUE TITLE
Search boxes searching for members should accept norwegian characters

### ISSUE THREAD

**Issue by Assios** [Samfundet/Samfundet#24]
simonra commented on 25 Sep 2014: "When searching for users (at least on windows machines) to for an instance add them to roles or steal their identities, you get no suggestions if you enter norwegian characters. This is a problem if the characters are near the beginning of a name, and you want to write a bit more of the name to filter the suggestions list further (those list can get annoyingly long)."

**Comment by Filip0** [comment]
Fixed by #134
