### ISSUE TITLE
Specify which ticket that's on the membership card when buying a ticket.

### ISSUE THREAD

**Issue by ghost** [Samfundet/Samfundet#262]
When you buy a ticket with "on membership card", the purchase confirmation page doesn't specify which _one_ ticket that is on the membership card. Today it lists the card number on each ticket in the table

**Comment by ghost** [comment]
(Added checkmark instead of listing up membership card number)
![image](https://user-images.githubusercontent.com/22009944/31045428-c4b6470c-a5e3-11e7-9522-a56ff3aff988.png)

**Comment by eirikvaa** [comment]
Duplicates issue https://github.com/Samfundet/Samfundet/issues/12.
