### ISSUE TITLE
Blog should throw error when publishing not chosen

### ISSUE THREAD

**Issue by stianste** [Samfundet/Samfundet#28]
Like with events, you must chose whether a blog post should be published immediately or at a set time. However, if you don't select one of them, the post doesn't get published at all. Because we want to have users consciously decide when the post is to be published, we should not allow them to accidentally finish the form without having filled in all the required fields.

A solution might be to toast the users when they forget the publishing option and try to submit?

**Comment by eirikvaa** [comment]
Not sure if this is still an issue, must be verified.

**Comment by eirikvaa** [comment]
You are not able to create a `Blog` without setting the `publish_at` attribute (since we `validate` it in the model), so this is not an issue anymore.
