### ISSUE TITLE
Delete the front page lock of an event when the event is deleted

### ISSUE THREAD

**Issue by KevinKristiansen** [Samfundet/Samfundet#319]
The front page lock of an event is not automatically deleted now, and this can be a problem if the front page lock tries to access a deleted event.

**Comment by alfiehub** [comment]
This should be handled using rails magic.

See here
https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-dependent

**Comment by snorrekr** [comment]
This seems not to be a problem anymore.
