### ISSUE TITLE
Add event to calendar button

### ISSUE THREAD

**Issue by Anderssorby** [Samfundet/Samfundet#373]
Do we need a "Add event to calendar" button on our events? might be practical. We could use something like https://www.addevent.com/

**Comment by eirikvaa** [comment]
Aren't people usually getting a Facebook event in their calendar?

**Comment by Anderssorby** [comment]
Not me at least; some people might find it useful.

**Comment by KevinKristiansen** [comment]
I feel like this would be extra work for the people creating the events

**Comment by snorrekr** [comment]
This is unnecessarly complicated therefor closing it.
