### ISSUE TITLE
Searching for the date of an event doesn't behave as expected

### ISSUE THREAD

**Issue by Assios** [Samfundet/Samfundet#43]
andereld commented on 20 Nov 2014: "Searching for an event currently includes the 'non_billig_start_time' database field in its query. This is the raw ISO 8601 datetime in UTC. There are at least three problems with this:

Most people won't search for '2014-11-20', but something like '20. november'
All of the event times are shifted one or two hours (depending on DST)
Event times are dispayed as 'kl. HH.MM' in Norwegian, but the search format needs to be 'HH:MM'
If event dates and times are to be included in the search, they need to be handled in a more flexible way."

**Comment by eirikvaa** [comment]
Closing as not relevant.
