### ISSUE TITLE
Investigate UI issues on mobile screens

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#458]
Eirik V reported the following problem on Android 8 1920x1080 phone.

![IMG_0008 JPG](https://user-images.githubusercontent.com/6376002/64971786-7d4fd500-d8a8-11e9-9bb0-68e805e05737.jpg)

**Comment by evgiz** [comment]
This issue was resolved with redesign.

There is ofc still room for improvement, but we should create new specific issues for any problems.
