### ISSUE TITLE
"Password to short message" looks pretty bad

### ISSUE THREAD

**Issue by stianste** [Samfundet/Samfundet#46]
When signing up as a new applicant: if the password is too short it looks like this:

![image](https://cloud.githubusercontent.com/assets/14058300/14262088/0b86a44c-fab4-11e5-97a7-8d483e7e66e2.png)

This might be a problem elsewhere as well

**Comment by stianste** [comment]
Should be "Passordet er for kort..." and so on, not an incomplete sentence.

**Comment by Frenje123** [comment]
Already fixed
