### ISSUE TITLE
End date of Samfundet closed period should be inclusive

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#460]
Investigate whether or not this is still an issue.

**Comment by eirikvaa** [comment]
@hegeaal This wasn't an issue, right?

**Comment by hegeaal** [comment]
No, it appeared to work fine :-)

8. okt. 2019 kl. 23:34 skrev Eirik Vale Aase <notifications@github.com<mailto:notifications@github.com>>:


@hegeaal<https://github.com/hegeaal> This wasn't an issue, right?

**Comment by hegeaal** [comment]
No, it appeared to work fine :-)

**Comment by eirikvaa** [comment]
Great, closing!
