### ISSUE TITLE
Inconsistent list of applicants with withdrawn applications

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#463]
Tollef Jørgensen on 29th of August 2019:

> **Søkere som har trekt søknad blir listet under "satt til reserve" (MEN IKKE ALLE)**
>
> skjer ved url:
> /opptak-administrasjon/opptak/36-hostopptak-2019/show_unflagget_applicants
> matcher ikke helt overens med lista over folk som ikke har blitt flagga!
> (kommunikasjonsgjengen)

**Comment by evgiz** [comment]
Closed, see #866
