### ISSUE TITLE
Show/export applicants without offerings from admin admission page

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#481]
It would be nice if there was a way to export applicants that have not gotten any offerings, but that were interested in other jobs so that for example UKA could get this list. In fall 2019 the admission was anonymized before UKA could get the list, which probably pissed them off quite a lot. Should improve this.

We should only need to export the email of the applicants.

**Comment by evgiz** [comment]
Not allowed due to GDPR<3
