### ISSUE TITLE
@current_user may be null in /soknader

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#493]
Per an exception that happened on www-beta:

```
A NoMethodError occurred while GET </soknader/> was processed by job_applications#index
Exception
undefined method 'job_applications' for #<Member:0x00007f5d3d72afa0>
```

This is because of the following code snippet, found in `job_applications_controller.rb`:

```ruby
def index
  @admissions = @current_user.job_applications.where(withdrawn: false).group_by { |job_application| job_application.job.admission }
end
```

At least RubyMine complains that `job_applications` _may_ be `null`. How this is possible I don't know, but since you have to be logged in at `/soknader` to do anything there, `@current_user` should never be `null`.

The error goes away with a change like the below:

```ruby
def index
  if @current_user.nil?
    @admissions = []
  else
    @admissions = @current_user.job_applications.where(withdrawn: false).group_by { |job_application| job_application.job.admission }
  end
end
```

But this will only circumvent the problem rather than fixing the underlying issue.

**Comment by konstahm** [comment]
Solved in Fix applicant login when no admission
