### ISSUE TITLE
Set name as link to admission

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#495]
The name (here `test`) should be named a link to the corresponding admission so it's easier to find older admissions (or the current one).

<img width="1203" alt="Skjermbilde 2019-10-04 16 24 06" src="https://user-images.githubusercontent.com/6376002/66215229-71934980-e6c3-11e9-9356-7f343097b6fe.png">

**Comment by evgiz** [comment]
Done. Also added titles to make it clear which admission you're viewing.
