### ISSUE TITLE
Download daily and weekly Lyche reservations to PDF

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#502]
Right now they can download in CSV format, but they have to manually format it in Excel and then export to PDF and then print, which is more than cumbersome. By downloading in PDF format directly they can print it directly.

**Comment by evgiz** [comment]
@Goshton is looking at ways to export tables of reservations for a given day/week to PDF format

**Comment by evgiz** [comment]
Too complicated for what its worth
Might look into again if KSG requests it
