### ISSUE TITLE
Replace "Direktesending" with some link to Lyche

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#508]
I propose that we replace the "Direktesending" menu item with some link that goes to Lyche. [UKA](https://uka.no) uses `Mat` and I think that would be a great menu name. One could also consider `Lyche`, but that might not be familiar to everybody. A third option might be `Reservation`, but it doesn't really communicate that it's about Lyche or food.

We should do this because "Direktesending" is rarely visited, and one has other means of making sure that people are able to go to the live show, for example by using a front page hijack.

**Comment by evgiz** [comment]
What about `Servering`?
