### ISSUE TITLE
Make it clear that old admissions are closed

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#511]
Old admission pages show tools which are not relevant for closed admissions:

<img width="726" alt="Screenshot 2019-10-10 at 20 43 25" src="https://user-images.githubusercontent.com/21267642/66597144-a6f5d680-eb9e-11e9-8b64-82e8fde8db94.png">
<img width="901" alt="Screenshot 2019-10-10 at 20 37 16" src="https://user-images.githubusercontent.com/21267642/66597034-65fdc200-eb9e-11e9-8e90-b6c320e9052e.png">

**Comment by eirikvaa** [comment]
It's nice to have these links after the admission, so we'll show them.
