### ISSUE TITLE
Fix tag search on image

### ISSUE THREAD

**Issue by eivrei** [Samfundet/Samfundet#513]
When clicking on a tag when viewing an image, the site breaks. 
![image](https://user-images.githubusercontent.com/22083159/66600095-0b1b9900-eba5-11e9-9b37-164a6c737a46.png)
![image](https://user-images.githubusercontent.com/22083159/66600149-238bb380-eba5-11e9-87b1-b628d4fea0c2.png)

**Comment by evgiz** [comment]
fixed 93fd9b55b7cc6a4a46e5cc5e826dd9773e0ae08c
