### ISSUE TITLE
Make a visual calendar reservation system for Lyche admins

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#529]
When Lyche has a large number of reservations, it is difficult to determine where a new reservation could fit. A list view is a bad way to get a good overview, so a visual calendar would be a large improvement. 

*Work in progress:*
<img width="1223" alt="Screenshot 2019-10-23 at 10 31 01" src="https://user-images.githubusercontent.com/21267642/67373620-409a8c00-f580-11e9-98b2-30a9ad060525.png">

**Requirements**
- Visualize reservations
- Show information on hover
- Easy way to edit reservations
- Show table numbers and capacity
- Show table description on hover
- Easily move reservation to different table
- Ability to view calendar for next few days
- Show user/internal comment on reservations
- Make it clear when a double booking has occured
- Vertical lines to more easily see time periods
- Easy way to mark comment as read?
- Other things?

**Accessibility idea**
In order to make the workflow better for people using the system, I suggest moving most tools to the main admin page with the calendar visualization in front. This way we can ensure all tools are easily and quickly accessible (see tool buttons on bottom of calendar).

**Comment by eirikvaa** [comment]
This probably duplicates #77. Maybe we can rename these issues such that one implements it for Lyche admins and one for customers (since that implementation is a bit different)?

**Comment by evgiz** [comment]
Didn't see #77, will look into how to better differentiate the two.

**Comment by eirikvaa** [comment]
Proposing to deploy this to production on Thursday :-)

**Comment by eirikvaa** [comment]
Close this and create smaller issues for the work left to be done, @evgiz?
