### ISSUE TITLE
Make it easier to register as an applicant

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#567]
There are two ways of registering as an applicant:

- A quite hidden button under /opptak
- If you write the incorrect username/password under /login for applicant

Some people go to jobs first, and then think of registering, in which they are met with this:
![image](https://user-images.githubusercontent.com/6376002/72628264-3fde7f80-394e-11ea-8616-7eb1c3a68e4b.png)
We could improve this to add a link or button to take them to registering.

**Comment by evgiz** [comment]
As a part of the redesign I also looked at this briefly, and my idea is to:
1. During opptak, feature a large "Apply!" button of some sort on the front page
2. On the opptak page, make the application button a prominent "call to action" button

**Comment by eirikvaa** [comment]
I like this! It makes sense to draw attention to an active admission on the front page.

**Comment by evgiz** [comment]
This has been resolved!
