### ISSUE TITLE
Filter which tables are visible in Lyche calendar

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#583]
Ability to filter out which tables are visible in Lyche calendar.

Priority from Lyche: Low
Should investigate use case!

**Comment by eirikvaa** [comment]
Working on this, @evgiz ?

**Comment by evgiz** [comment]
Put on hold, Lyche has many requests which are of much higher priority

**Comment by evgiz** [comment]
This wont happen, complex to do with little payoff
