### ISSUE TITLE
Lyche google search

### ISSUE THREAD

**Issue by Filip0** [Samfundet/Samfundet#60]
When searching for lyche reservasjon on google the text says "linken - Samfundet.no"

![lyche](https://cloud.githubusercontent.com/assets/1095722/14366806/d06bfbd8-fd14-11e5-9b52-50d24a643780.png)

**Comment by Assios** [comment]
Seems like this was automatically fixed by Google
![title](https://cloud.githubusercontent.com/assets/1413265/14437053/cf840298-001f-11e6-8e01-81abc8ceb57f.png)

**Comment by cristeahub** [comment]
In DuckDuckGo as well. I guess this was some part of Google's cache that wasn't updated or something similar.
![image](https://cloud.githubusercontent.com/assets/1488921/14437437/7b6a2212-0021-11e6-8641-07121baab0b4.png)

Other searches seems to work as well, closing this out.
![image](https://cloud.githubusercontent.com/assets/1488921/14437469/9c374402-0021-11e6-83e2-5de529656f5e.png)
