### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#624]
Redaksjonen talked about the ability to add several events at the same time (example: "24 mislykkede nordmenn" series that have x number of the same events).

This would probably also demand another way of viewing events that are in the same series or are requrring.

**Comment by evgiz** [comment]
The simplest way to achieve this would be to have an "add recurring times" which simply duplicates the event X times for specified dates. A one-to-many relationship for dates would however be better.

**Comment by evgiz** [comment]
Closed, this will be solved better in #231
