### ISSUE TITLE
Consider moving list of old admissions to admission_admin

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#634]
We should  consider moving the list of old admissions out of the `/opptak` page and under `admission_admin` as that's really where it belongs. This should maybe be a separate controller, and we could provide a link to it in the admissions admin applet.

This way we can avoid mixing admin/non-admin things on the `/opptak` page.

![image](https://user-images.githubusercontent.com/6376002/76555366-c7042b80-6497-11ea-9389-bec918555f31.png)

**Comment by evgiz** [comment]
Relevant PR: #713
