### ISSUE TITLE
Explore 'attractor' gem for visualizing complexity/churn

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#670]
`attractor` is a *code complexity metrics visualization and exploration tool for ruby and javascript*. It uses the `complexity * churn` metric to point to places in our code where refactoring could be most beneficial. Read more about the approach [here](https://medium.com/better-programming/why-i-made-my-own-code-quality-tool-c44b40ceaafd). Consider integrating this gem into the project like this

```
gem 'attractor'
gem 'attractor-ruby'
```

and then run `attractor report` to see the report.

**Comment by snorrekr** [comment]
Closing issue as we realistically are not going to do this.
