### ISSUE TITLE
Explore 'brakeman' gem for static security vulnerability analysis

### ISSUE THREAD

**Issue by eirikvaa** [Samfundet/Samfundet#671]
[Brakeman](https://github.com/presidentbeef/brakeman) can be used to found potential security vulnerabilities like XSS vulnerabilities, et cetera. Integrate with

```
group :development do
  gem 'brakeman'
end
```

and run `brakeman -o output.txt` to get a report.

**Comment by snorrekr** [comment]
Closing issue as we realistically are not going to do this.
