### ISSUE TITLE
System accept Lyche reservations when there are no available tables

### ISSUE THREAD

**Issue by hegeaal** [Samfundet/Samfundet#697]
The system accepts reservations even though there are no available tables. The guest are assigned to a table called "missing table" which the system sees as available all the time, so the restaurant is never seen as fully booked.

**Comment by evgiz** [comment]
I'll fix this while @hegeaal and @Frenje123 starts working on the visual interface for customers described in #77

**Comment by evgiz** [comment]
Fixed by pr #705
