### ISSUE TITLE
Logging in as member when already logged in

### ISSUE THREAD

**Issue by Frenje123** [Samfundet/Samfundet#720]
If you access this link: https://samfundet.no/logg-inn?redirect_to=%2Fsoknader, while you are logged in as a member, from the admissions page, and log in again as member with your correct email and password, an error will be occur. There should be a login check in one of the controllers (likely site_controller.rb), which will output a message "you are already logged in", instead of outputting the login form again. 

NB: This error will however not occur from https://samfundet.no/logg-inn

**Comment by konstahm** [comment]
solved in branch Fix applicant login when no admission
