### ISSUE TITLE
Make sulten reservation model support multiple tables

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#743]
When #739 is resolved, reservations for multiple tables will simply be duplicated.
The better solution is to have a one-to-many relationship from reservation to tables so that the reservations are connected.

This is more complex and requires various changes in the sulten system.  This issue will be quite hard and requires a fair amount of work to solve, so I would wait to see if Lyche really needs this. It is really only important when reservations must be changed (they'd have to change each one individually).

**Comment by snorrekr** [comment]
This overlaps with #451
