### ISSUE TITLE
Improve the documents page

### ISSUE THREAD

**Issue by alfiehub** [Samfundet/Samfundet#76]
The document page (saksdokumenter) is not structured in a good way. This makes it hard to navigate through it, especially when the amount of documents increases.

A possible fix would be to have some kind of drop-down menus for each year / month.
Everything is better than how it is currently.

**Comment by Anderssorby** [comment]
![skjermdump fra 2016-04-21 22-51-17](https://cloud.githubusercontent.com/assets/6331075/14723875/77ab357c-0813-11e6-9e4b-c548abe2d4b7.png)
 Litt bedre
