### ISSUE TITLE
Make admin customization tools for info boxes on front page

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#764]
Depends on #763

Create an admin page to create these customization boxes directly on the website.

To achieve this we need a new model in the database which should have:
- Start and end time for info box
- Image
- Description 
- Button text (eg. "read more")
- URL link (eg. to new building page)

Should also support localization, so text fields must have translations as well. 

It would also be cool to have different boxes, some of which are a single tile wide and others that are two tiles wide.

**Comment by snorrekr** [comment]
- [ ] låse posisjon
- [ ] stylings-testing, mobil
- [x] mulighet til å ikke ha bilde (bruke true/false)
- [ ] bredde
- [x] boks rundt edit
- [x] Gjøre tid required
- [x]  redirect to root 
- [x] x2 scss
- [x] tid i index (sorter etter tid)
- [x] norsk/engelsk route

**Comment by evgiz** [comment]
Closed with #785
