### ISSUE TITLE
Visualization for customers to see when free reservations are possible

### ISSUE THREAD

**Issue by alfiehub** [Samfundet/Samfundet#77]
The users of the Sulten system has requested a feature that allows them to see how much of the restaurant is booked.

"Måte å se oversikt over bord-opptatt på en oversiktlig måte, vanskelig å se hvor mye av restauranten som er opptatt til enhver tid"

**Update 8/10-19**
After a meeting with Lyche it was proposed to have a visual representation where time would be on the _x_ axis and tables on the _y_ axis, which would show, in a nice way, what tables are taken at what time. Moved to #529

**Update 24/10-19**
Make a visual system for customers. Could be built as a variation of implementation of #529 
Customers should not be able to access data in the same amount of detail to ensure confidentiality etc. Perhaps 1 axis that shows if some periods are fully booked is enough? Investigate.

**Comment by evgiz** [comment]
This was discussed again yesterday, and will be added on the new Lyche site in order to prevent excessive rejections when users create reservations, particularly with respect to current COVID-19 restrictions.

**Comment by evgiz** [comment]
> Make a visual system for customers. Could be built as a variation of implementation of #529

We'll create a new visualisation in order to not expose too much information to customers.
The frontend will work somewhat like this:

1. Enter number of people
2. Choose a date
3. Available times will show up, simply select one of them
