### ISSUE TITLE
Investigate problems with registering as applicant using international phone number

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#775]
I suspect that certain international phone numbers make it difficult to register as an applicant, at least in some web browsers. 

Must investigate further!

**Comment by magsyg** [comment]
Looked at the issue were no problems with phone numbers, could use +32 88282828 and +1 224 242525 without fail. 
The accepted chars are numbers and +, but not ()- so people who typed the number as +1 (232)-2525251, which is standard american.
This would fail if they tried that, but they should be able to type it correctly without those signs, one solution could be implementing helper text for correct formating

**Comment by magsyg** [comment]
The issues from exchange students are most probably from them being confused by the seperate registrations
Some of the mails said they registered as volunteer and tried to use member functions, another tried to login in as applicant as member. 

The best solution to this, may be to redesign the application model, to a foreign key to member, which can be deleted when everything is over

**Comment by evgiz** [comment]
No problems with this for a couple admissions, probably just user error 🤷‍♂️
