### ISSUE TITLE
Show when reservations was placed/mark new ones

### ISSUE THREAD

**Issue by alfiehub** [Samfundet/Samfundet#78]
I dont what's the best solution to this, but the easiest one is to show when each reservation was placed.

"Lett kunne se hva som er nye bestillinger, sjekker man flere ganger er det vanskelig å se hva som har kommet inn nylig. Timestamp i adminpanelet?"

**Comment by snorrekr** [comment]
@nemisis84 does pr #905 solve this, if so close the issue.
