### ISSUE TITLE
Add questions to events

### ISSUE THREAD

**Issue by alfiehub** [Samfundet/Samfundet#83]
LØK has requested functionality that allows them to add questions to an event that users can answer after they've purchased a ticket.

A good way to solve this is to add the poll to the ticket purchase success page.
We also want to have some kind of default question added to the poll, asking where the purchaser found out about the evnet.

So long story short: add questions to events and answers to these questions. Let users answer these questions after they've purchased tickets for each event. Let admins add and remove questions and answers for each event. We obviously also need some view to display the results for each event.

**Comment by Anderssorby** [comment]
TODO:
- [x] Display when purchased tickets
- [x] Edit for survey not working
- [x] Ordering for questions
- [x] Answer form
- [x] Answer overview
- [x] Add welcome message to survey
- [x] Handle errors in answers
- [x] Add validation to answers
- [ ] Export function for survey data
- [ ] Update answer when duplicate
- [ ] CSRF token not working in ajax
- [ ] Add ordering of appearance for questions in survey
- [ ] Add multiple selection answer
- [ ] Add custom text input answer

Optional ideas:
- [ ] More modern javascript...
- [ ] Non-javascript option
- [ ] Competition form at the end

**Comment by Anderssorby** [comment]
Markedsmøte Tekst bør være gjennomtenkt. Mulig å velge flere alternativer. Automatisk videre. Startknapp. Mulig å endre svar. Popup. Lukk vindu knapp. Når ferdig ikke mulig å gå tilbake. Statistikk som for opptak.

**Comment by eirikvaa** [comment]
Have to figure out how far along this issue is.

**Comment by eirikvaa** [comment]
Closing because we haven't gotten any requests for this lately and rumors has it that it was scrapped.
