### ISSUE TITLE
Investigate relevance of "interested in other jobs" and "reserved or not flagged" in admissions

### ISSUE THREAD

**Issue by evgiz** [Samfundet/Samfundet#866]
With the new admission overview page, these pages are probably not used a lot.
Should they be removed/changed in any way?

**Comment by snorrekr** [comment]
As this only affects us and mg-nestleder i see no reason to change it, i asked current mg-nestleder if she found it confusing or problematic in any way, but she answered that she mainly ignored the buttons. If in the future there are complaints we can look into it again, but before that we leave it as is.
