### ISSUE TITLE
Add information about admission-video 

### ISSUE THREAD

**Issue by snorrekr** [Samfundet/Samfundet#869]
This admission mg-video had finished a new admissionsvideo, nestleder ran into problems trying to display it. This is because the link you need to provide must be an embeded youtube link. We should add an explaining text so that this doesnt become an issue' in the future.
As well as this we should update the default admissionsvideo to the new version.

**Comment by snorrekr** [comment]
This is the newest link https://www.youtube.com/embed/-nYQb8_TvQ4

**Comment by oscarahalvorsen** [comment]
closed with #870
