### ISSUE TITLE
Investigate relevance of path issue with contact info

### ISSUE THREAD

**Issue by Frenje123** [Samfundet/Samfundet#909]
Going to the link [https://www.samfundet.no/informasjon/17-korona-virus](https://www.samfundet.no/informasjon/17-korona-virus) will for some reason direct you to the same place as [https://www.samfundet.no/informasjon/kontaktinfo](https://www.samfundet.no/informasjon/kontaktinfo). They refer to the same document, but with different URLs.

This also only happens in production.

**Comment by nemisis84** [comment]
The issue isn't spesific to the korona-virus text. It's rather a functionality that you can write anything you want behind an id without it impacting where you are directed. This is also true for other paths such as arrangementer, and isn't really an issue.
