### ISSUE TITLE
Rework events archive and archive search page

### ISSUE THREAD

**Issue by alfiehub** [Samfundet/Samfundet#92]
Its ugly. We need to fix it.

Archive search results only shows each events date, which is confusing because the event might be from 2014. It's also sorted wrong, from oldest to newest and should be from newest to oldest (maybe?).
The events table at the archive view should be styled a bit

So yea, the whole thing needs a bit of love

**Comment by Filip0** [comment]
Event search breaks when javascript is disabled. Added a quickfix for part of the problem #95 
Agree that it should be fixed.

**Comment by eirikvaa** [comment]
Agreed that the page needs some love, though it's quite clear when an event is from (which year) and it's sorted correctly.

**Comment by eirikvaa** [comment]
Closing because it seems the bugs have been fixed. Will create a new issue for UI related work.
